CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
#AUTOCORRECT_ENABLE = yes
COMBO_ENABLE = yes
NKRO_ENABLE = yes
#RGBLIGHT_ENABLE = yes

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
# AVR_USE_MINIMAL_PRINTF = yes